name = "math-mcp-client"
main = "fixed-client.js"
compatibility_date = "2024-03-08"

# Configure workers_dev to true to enable the workers.dev subdomain
workers_dev = true

# Specify that this is an ES module worker
compatibility_flags = ["nodejs_compat"] 